---
ID: "acdb7d9e-11a0-4420-b601-bceab2b99bf3"
Parent: "adf03ef2-3d8b-4d46-9705-4e3c2444d23b"
Template: "adf03ef2-3d8b-4d46-9705-4e3c2444d23b"
Path: "/sitecore/templates/Project/sitecoredemo-jp/JSS Settings/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221215T082758Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "028a58af-b931-4a5f-9b85-f466c41d757d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221215T082758Z
